spring:
  application:
    name: proovy
  datasource:
    url: jdbc:postgresql://localhost:5432/deundeun_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.deundeun
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: DEBUG

server:
  servlet:
    session:
      timeout: 30m

naverpay:
  return-url: http://localhost:3000/wallet/charge/return